# Generated by Django 2.2.1 on 2019-05-17 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='dt_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 17, 10, 1, 14, 114366, tzinfo=utc)),
        ),
    ]
