# Generated by Django 2.2.1 on 2019-05-17 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190517_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='dt_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 17, 19, 1, 22, 906928, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('yes', 'yes'), ('free', 'free')], default='NOT_ASSIGN', help_text='deliverd or not delivered', max_length=128),
        ),
        migrations.AlterField(
            model_name='food',
            name='task',
            field=models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('declined', 'declined'), ('cancelled', 'cancelled')], default='NEW_TASK', help_text='Accepts or not', max_length=128),
        ),
    ]
